name: GitHub Actions Demo
on:
  push:
    branches: [ workflow, main, release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      key:
        description: sample key
        required: true
        default: snapshot

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Set PEM Version
        run: |
          echo "PEM_VERSION=8.5.0" >> $GITHUB_ENV
          echo "RELEASE_VERSION=1')" >> $GITHUB_ENV
      - name: disable step testing
        if: ${{ false }}  # disable for now
        run: |
          echo "I am a testing step"
      - name: List files in the repository
        run: |
          pwd
          whoami 
          mkdir -p builds.edb/debian/x86_64/
          ls ${{ github.workspace }} | tee builds.edb/debian/x86_64/edb-pem-files1-deb11_amd64.txt
          ls ${{github.workspace}} | tee builds.edb/debian/x86_64/edb-pem-files2-deb11_amd64.txt
      - name: Upload packages to artifactory
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: builds.edb/debian/x86_64/edb-pem*deb11_amd64.txt
      - name: sample action
        uses: ./actions/sample
        with:
          key: ${{ inputs.key }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Test-GitHub-Actions:
    if: ${{ false }}  # disable for now
    needs: [ Explore-GitHub-Actions ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically run after Explore-GitHub-Actions"
      - name: disable step testing
        if: ${{ false }}  # disable for now
        run: |
          echo "I am a testing step"

  Branch-Specific-GitHub-Actions:
    if: ${{ github.ref != 'refs/heads/main' }}
    needs: [ Explore-GitHub-Actions ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job is branch specific"
      - name: step testing
        run: |
          echo "I am a testing step on non-master branch"

