name: Matrix-Job-Builder

env:
  REPO: "dev"
  NAME: "Jim"
on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      version:
        description: 'DB Version'
        required: true
        default: 'v14'
        type: choice
        options:
        - v14
        - v13
        - v12
        - v11
      architects:
        description: 'Architecture'
        required: true
        default: 'x86'
        type: choice
        options:
        - x86
        - ppc
        - s390

jobs:
  two-dimensions-matrix-job:
    runs-on: ubuntu-latest

    env:
      PPAS_VERSION: "14"

    strategy:
      matrix:
        VERSION_CODE: [ ${{ inputs.version }} ]
        VERSION_NAME: [ ${{ inputs.architects }} ]

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Display ${{matrix.VERSION_CODE}} value
        run: |
          echo "${{env.PPAS_VERSION}}"

      - name: Say hello to ${{matrix.VERSION_NAME}}
        run: |
          echo "Hello, ${{matrix.VERSION_NAME}} ! This is ${{env.NAME}} from ${{env.REPO}}"

