name: Matrix-debug

on:
  push:
    branches: [ jw/matrix ]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

  matrix-job:
    runs-on: ubuntu-latest
    needs: prepare

    strategy:
      matrix:
        distro: [ ubuntu ]
        distro-version: [ 20.04, 22.04 ]
        arch: [ amd64 ]
        include:
          - distro: [ debian ]
            distro-version: [ 10, 11 ]
            arch: [ amd64 ]
          - distro: [ el ]
            distro-version: [ 7, 8, 9]
            arch: [ amd64, ppc64le, amd64 ]
          - distro: [ sles ]
            distro-version: [ 12sp5, 15sp4 ]
            arch: [ amd64, ppc64le, amd64 ]
          - distro: [ windows ]
            distro-version: [ 2019 ]
            arch: [ x64 ]
        exclude:
          - distro: [ el]
            distro-version: [ 7]
            arch: [ ppc64le ]

    steps:
      - name: Display matrix value
        shell: bash
        run: |
          echo "distro: ${{ matrix.distro }}
          echo "distro-version: ${{ matrix.distro-version }}
          echo "arch : ${{ matrix.arch }}
          touch ${{ matrix.distro }}-${{ matrix.distro-version }}-${{ matrix.arch }}.txt

  collect:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Display matrix value
        shell: bash
        run: |
          ls -altr *.txt

