
name: YARN Installation

on:
  workflow_dispatch:

jobs:
  install-yarn
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install yarn
        shell: bash
        run: |
          npm install yarn -g
          yarn set version 1.22.19

      - name: Check versions
        shell: bash
        run: |
          node --version
          yarn --version
          npm --version

